# -*- coding: utf-8 -*-
"""Numpy

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u8OVgos5cRN_BkcPolTsoLgV_cgpVvCs
"""

import numpy as np
arr=np.array([1,2,3,4,5])# 1 dimensional array
print(arr)
print(arr.ndim)# checks the dimension of the ndarray

import numpy as np
arr=np.array([[1,2,3],[4,5,6]])# 2 dimensional array
print(arr)
print(arr.ndim)# checks the dimension of the ndarray

import numpy as np

arr = np.array([[[1,3],[1,2],[4,5]]])# 3 dimensional array
print(arr)
print(arr.ndim)# checks the dimension of the ndarray

import numpy as np

arr = np.array([[10,20,30,40],[50,60,70,80]])
print(arr.shape)# show shape of array
new=arr.reshape(4,2)# reshape the array
print(new)

import numpy as np
arr = np.array([1,2,4])
arr1=np.array([3,4,5])
new = np.concatenate((arr,arr1))# add 2 arrays
print(new)

import numpy as np
a = np.array(["HELLO","WORLD"])
b=np.array(["welcome","numpy"])
re=np.char.add(a,b)# add or join 2 arrays
print(re)

import numpy as np
str="hello world"
b=np.char.upper(str)# upper the string
print(b)
b=np.char.lower(str)# lower the string
print(b)
print(str)
a=np.char.replace(str,'hello','my')# replace new string or char
print(a)

import numpy as np

a= np.array([10,20,30])
b=np.array([40,50,60])
c=np.add(a,b)# ADDITION OF 2 ARRAYS
d=np.subtract(a,b)# SUBTRACTION OF 2 ARRAYS
print("Addition    : ",c)
print("Subtraction : ",d)

import numpy as np
arr=np.array([[4,3,8],[10,2,3],[5,8,24]],dtype='int64')
print(arr.ndim)# return no.of dimension
print(arr.dtype)# return the datatype of array
print(arr.size)# return the size or total elments of array
print(arr.shape)# return shape of array(row,column)
print(arr.itemsize)# return itemsize
print(arr.data)# return memory of array

import numpy as np
arr=np.array([[4,3,8],[10,2,3],[5,8,24]],dtype='int64')
print(np.amin(arr))# minimum of array
print(np.amin(arr,axis=0))# minimum of arrary of row or columns
print(np.amax(arr))# maximum of array
print(np.max(arr))# maximum of array
print(np.amax(arr,axis=1))# maximum of arrary of row or columns
print(np.median(arr,axis=0))# return median of array
print(np.mean(arr))# return mean of array
print(np.std(arr))# return standard divison of array
print(np.var(arr))# return variance of array
print(np.percentile(arr,40))# return percentile of array

import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
np.where(arr%2==0,"Even","Odd")# where function
co=[arr<5,arr>5]# conditions
cho=[arr**2,arr+5]# choice list
np.select(co,cho,default=arr)# select function

import numpy as np
arr = np.array([1,2,3,4,5])
print("1 dimension indexing :",arr[1])# return 1 element of array
arr1= np.array([[1,2,3,4],[5,6,7,8]])
print("2 dimension indexing :",arr1[0,2])# return 0,2 element of array
arr1= np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print("3 dimension indexing :",arr1[0,2,3])# return 0,2,3 element of array

import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[2:])# 1d Array Slicing
print(arr[:-1])# negative index Slicing
arr1= np.array([[1,2,3,4],[5,6,7,8]])
print(arr1[1,1:])
arr2= np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(arr2[0,1:,2:])

import numpy as np

print(np.arange(2,10))# return give values
np.arange(2,10,1.5)#arnage in give order wise